import { Legal } from "@/components/Legal";
export const metadata = { title: "Child Safety — Lullawood" };
export default function Page() {
  return (
    <Legal title="Child Safety" updated="25 June 2026">
      <p>Lullawood is made for children, and their safety shapes every decision we make. Here is how we keep the experience gentle, age-appropriate, and in your hands.</p>

      <h2>How stories are kept safe</h2>
      <ul>
        <li><strong>Gentle by design.</strong> Every story is written to wind down toward sleep — warm, calm, and reassuring. No peril, no violence, nothing frightening.</li>
        <li><strong>Safety-reviewed.</strong> Stories are generated by AI and passed through automated safety checks before they ever reach your child, designed to filter out anything inappropriate.</li>
        <li><strong>Age-aware.</strong> We adjust vocabulary, length, and tone to the age range you set.</li>
        <li><strong>You set the tone.</strong> You choose the profile and any gentle weekly theme. Nothing appears in a story that you haven&apos;t shaped.</li>
      </ul>

      <h2>We&apos;re open about AI</h2>
      <p>Lullawood&apos;s stories are created with AI. We tell you that plainly because you deserve to know exactly what your child is hearing. AI can occasionally produce something unexpected; our safety checks are designed to catch it, and you can report anything that doesn&apos;t feel right so we can act quickly.</p>

      <h2>What we will never do</h2>
      <ul>
        <li>We will never show advertising to your child.</li>
        <li>We will never sell your child&apos;s data, or use it to build advertising profiles.</li>
        <li>We will never ask a child for personal information.</li>
      </ul>

      <h2>You&apos;re in control</h2>
      <p>You can review stories, change or delete a profile, and cancel at any time. Stories are delivered to <strong>you</strong> — the parent — to read aloud or play, so a screen never has to come between you and your child at bedtime.</p>

      <h2>Reporting a concern</h2>
      <p>If a story ever feels off, please tell us at <a href="mailto:safety@lullawood.com">safety@lullawood.com</a>. We read every report and respond quickly. Keeping Lullawood a safe, trusted place is the most important thing we do.</p>
    </Legal>
  );
}
